/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ratovibot;

/**
 *
 * @author Montasser
 */
public class RatovibotForm extends javax.swing.JFrame {
    
    /**
     * Creates new form RatovibotForm
     */
   
    
    public RatovibotForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        desktopP = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        comptes = new javax.swing.JMenu();
        Acompte = new javax.swing.JMenuItem();
        Lcompte = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        villages = new javax.swing.JMenu();
        Lvillages = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RatoviBot");

        desktopP.setToolTipText("");

        javax.swing.GroupLayout desktopPLayout = new javax.swing.GroupLayout(desktopP);
        desktopP.setLayout(desktopPLayout);
        desktopPLayout.setHorizontalGroup(
            desktopPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        desktopPLayout.setVerticalGroup(
            desktopPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        comptes.setText("Comtes");

        Acompte.setText("Add compte");
        Acompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcompteActionPerformed(evt);
            }
        });
        comptes.add(Acompte);

        Lcompte.setText("Compte Liste");
        Lcompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LcompteActionPerformed(evt);
            }
        });
        comptes.add(Lcompte);

        jMenuItem6.setText("Connecter");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        comptes.add(jMenuItem6);

        jMenuBar1.add(comptes);

        villages.setText("Villages");
        villages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villagesActionPerformed(evt);
            }
        });

        Lvillages.setText("liste villages");
        Lvillages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LvillagesActionPerformed(evt);
            }
        });
        villages.add(Lvillages);

        jMenuBar1.add(villages);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LcompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LcompteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LcompteActionPerformed

    private void AcompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcompteActionPerformed
        
    }//GEN-LAST:event_AcompteActionPerformed

    private void villagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villagesActionPerformed
             
    }//GEN-LAST:event_villagesActionPerformed

    private void LvillagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LvillagesActionPerformed
        
                 Villages vl = new Villages() ;
                
                desktopP.add(vl);
                vl.show();
                
    }//GEN-LAST:event_LvillagesActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       Compte cx =new Compte() ; 
                
                desktopP.add(cx);
                cx.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RatovibotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RatovibotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RatovibotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RatovibotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RatovibotForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acompte;
    private javax.swing.JMenuItem Lcompte;
    private javax.swing.JMenuItem Lvillages;
    private javax.swing.JMenu comptes;
    private javax.swing.JDesktopPane desktopP;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenu villages;
    // End of variables declaration//GEN-END:variables
}
