/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ratovibot;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

/**
 *
 * @author Montasser
 */
public class Villages extends javax.swing.JInternalFrame {

    /**
     * Creates new form Villages
     */
     
    public Villages() {
        initComponents();
       
       
        
    }
         
         Ratovi r1 = Ratovi.r1 ;  
            WebDriver driver=r1.getDriver();
            DefaultListModel dlmv ;
            DefaultListModel dlmb ;
            public List<WebElement> chmps  ; 
            public List<WebElement> list ; 
            public List<WebElement> builds ;
            
            public String lien ;
            public  String selectval ;
            public  String selectb ;
            public void inilist(List<WebElement> list){
                this.list = list ;
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Vname = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Namev = new javax.swing.JLabel();
        Vtitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("listvillages");

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "builds" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jList2FocusGained(evt);
            }
        });
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jButton4.setText("center");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("champs");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Vtitle.setText("Title");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(Namev, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(Vtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(Vtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Namev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Village List","" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("charger");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(">>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addGap(29, 29, 29))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(Vname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(617, 617, 617))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Vname)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private static final Logger LOG = Logger.getLogger(Villages.class.getName());

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         driver.findElement(By.xpath("//a[@id='karia']")).click();
        dlmv=new DefaultListModel() ;

        list=driver.findElements(By.xpath("//*[@id='side_info']//table[1]//tbody[1]//tr//td//div//a")) ;
        inilist(list);
        for (WebElement url : list) {
            //url.getAttribute("href"));
        try{
            dlmv.addElement(url.getText());
            // System.out.println(dlm.getElementAt(2)) ;
            // System.out.print(dlm.elementAt(1));
        }catch(Exception e ) {
            e.getMessage();
        }

        }
        jList1.setModel(dlmv);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        selectval = (String)jList1.getSelectedValue() ;

        list.stream().filter((url) -> (url.getText().equals(selectval))).forEach((url) -> {
            lien=url.getAttribute("href") ;

        });

        if(!(lien.equals(""))){

            driver=r1.getDriver();
            driver.get(lien);
            chmps= driver.findElements(By.xpath("//map[@id='rx']//area")) ;
            dlmb=new DefaultListModel() ;
            for (WebElement url : chmps) {
                //url.getAttribute("href"));
            try{
                dlmb.addElement(url.getAttribute("title"));

                // System.out.println(dlm.getElementAt(2)) ;
                // System.out.print(dlm.elementAt(1));
            }catch(Exception e ) {
                e.getMessage();
            }

        }
        jList2.setModel(dlmb);
        }

        dlmv=new DefaultListModel() ;
        list=driver.findElements(By.xpath("//*[@id='side_info']//table[1]//tbody[1]//tr//td//div//a")) ;
        for (WebElement url : list) {
            //url.getAttribute("href"));
        try{
            dlmv.addElement(url.getText());
            // System.out.println(dlm.getElementAt(2)) ;
            // System.out.print(dlm.elementAt(1));
        }catch(Exception e ) {
            e.getMessage();
        }

        }
        Vtitle.setText(selectval);
        Vtitle.setVisible(true);
        jList1.setModel(dlmv);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        selectval = (String)jList1.getSelectedValue() ;

        list.stream().filter((url) -> (url.getText().equals(selectval))).forEach((url) -> {
            lien=url.getAttribute("href") ;

        });

        if(!(lien.equals(""))){

            driver=r1.getDriver();
            driver.get(lien);
            chmps= driver.findElements(By.xpath("//map[@id='rx']//area")) ;
            dlmb=new DefaultListModel() ;
            for (WebElement url : chmps) {
                //url.getAttribute("href"));
            try{
                dlmb.addElement(url.getAttribute("title"));

                // System.out.println(dlm.getElementAt(2)) ;
                // System.out.print(dlm.elementAt(1));
            }catch(Exception e ) {
                e.getMessage();
            }

        }
        jList2.setModel(dlmb);
        }

        dlmv=new DefaultListModel() ;
        list=driver.findElements(By.xpath("//*[@id='side_info']//table[1]//tbody[1]//tr//td//div//a")) ;
       inilist(list);
        for (WebElement url : list) {
            //url.getAttribute("href"));
        try{
            dlmv.addElement(url.getText());
            // System.out.println(dlm.getElementAt(2)) ;
            // System.out.print(dlm.elementAt(1));
        }catch(Exception e ) {
            e.getMessage();
        }

        }
        jList1.setModel(dlmv);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        driver.findElement(By.xpath("//a[@id='markaz']")).click();
        builds=driver.findElements(By.xpath("//map[@id='map2']//area")) ;

        dlmb=new DefaultListModel() ;
        builds.stream().forEach((url) -> {
            //url.getAttribute("href"));
        try{
            dlmb.addElement(url.getAttribute("title"));

            // System.out.println(dlm.getElementAt(2)) ;
            // System.out.print(dlm.elementAt(1));
        }catch(Exception e ) {
            e.getMessage();
        }
        });
        jList2.setModel(dlmb);

        dlmv=new DefaultListModel() ;
        list=driver.findElements(By.xpath("//*[@id='side_info']//table[1]//tbody[1]//tr//td//div//a")) ;
        list.stream().forEach((url) -> {
            //url.getAttribute("href"));
        try{
            dlmv.addElement(url.getText());
            // System.out.println(dlm.getElementAt(2)) ;
            // System.out.print(dlm.elementAt(1));
        }catch(Exception e ) {
            e.getMessage();
        }
        });
        jList1.setModel(dlmv);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jList2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList2FocusGained
            
    }//GEN-LAST:event_jList2FocusGained

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
            
         selectb = (String)jList2.getSelectedValue() ;
        
       
        chmps.stream().filter((url) -> (url.getAttribute("title") .equals(selectb))).forEach((url) -> {
            lien=url.getAttribute("href") ;
            
        });
       /*  r1.builds.stream().filter((url) -> (url.getText().equals(selectb))).forEach((url) -> {
            lien=url.getAttribute("href") ;

        });*/

        if(!(lien.equals(""))){
            driver=r1.getDriver();
            driver.get(lien);
            dlmb=new DefaultListModel() ;
            for (WebElement url : chmps) {
                //url.getAttribute("href"));
            try{
                dlmb.addElement(url.getAttribute("title"));

                // System.out.println(dlm.getElementAt(2)) ;
                // System.out.print(dlm.elementAt(1));
            }catch(Exception e ) {
                e.getMessage();
            }

        }
       jList2.setModel(dlmb);
        }

       dlmv=new DefaultListModel() ;
               for (WebElement url : list) {
           // System.out.println(url.getAttribute("href"));
        try{
            dlmv.addElement(url.getText());
            // System.out.println(dlm.getElementAt(2)) ;
            // System.out.print(dlm.elementAt(1));
        }catch(Exception e ) {
            e.getMessage();
        }

        }
        jList1.setModel(dlmv);
        
    }//GEN-LAST:event_jList2MouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Namev;
    private javax.swing.JLabel Vname;
    private javax.swing.JLabel Vtitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    
}
